### ISSUE TITLE
Issue in iOS

### ISSUE THREAD

**Issue by ahmed-zekry** [vidinoti/cordova-plugin-PixLive#9]
Hello,

The plugin working in android without any issues but in iOS it gives me a black screen with a red ban sign. check the attached screenshot
![WhatsApp Image 2019-07-14 at 5 05 44 PM](https://user-images.githubusercontent.com/12230439/61185626-d0649c00-a65b-11e9-9411-2977c02924f1.jpeg)

**Comment by JL-Vidinoti** [comment]
Hello,
This happens if you have an invalid license (either your license has expired or you don't have configured your application correctly).

First, login to [V-Director](https://armanager.vidinoti.com) and go to "SDK > My applications". Check that your application is correctly configured (correct platform (iOS/Android) and correct app bundle id/package name).
Note that if you have an application for Android and iOS, you must configure both.

Secondly, check that your license key is correct and valid (go to "SDK > My Licenses")
